import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv()
db_url = os.getenv("DATABASE_URL")
engine = create_engine(db_url)

with engine.connect() as conn:
    # Delete existing admin if any
    conn.execute(text("DELETE FROM users WHERE username = 'admin'"))

    # Insert new admin with ALL required fields
    # id will be auto-generated by PostgreSQL
    sql = text("""
        INSERT INTO users (username, email, mobile, password, role, is_approved) 
        VALUES ('admin', 'admin@safetracker.com', '0000000000', 'admin123', 'admin', true)
    """)
    conn.execute(sql)
    conn.commit()
    print("Admin 'admin' with password 'admin123' created successfully.")
